### ISSUE TITLE
Should rename `Match` class 

### ISSUE THREAD

**Issue by koutalou** [splathon/splathon-api#16]
## What

* `Match` ってClass、FlutterSDK側(lib/core/pattern.dart) で使ってるっぽくて衝突してビルドできないぽ〜
* :tanomu::tanomu: rename `Match`~

**Comment by haya14busa** [comment]
卍？？
dart って名前空間ないんです？それか同じ名前空間使ってるのか。。。

さすがにクライアント側でなんとかできないとおかしいとおもうけど、できなかったらなんか適当に使える名前にしてp-rしてほしさ。

**Comment by koutalou** [comment]
一応こんな感じで解決できることは分かった。
```
import 'package:openapi/api.dart' as API show Match;
import 'package:openapi/api.dart' hide Match;
```

Matchだけこんな呼び出し `API.Match`, 他はそのまま呼び出し

なのでIssueはCloseで大丈夫です！さんきゅ卍！

**Comment by koutalou** [comment]
嘘だった、ダメそう。。
アプリ側は良いけどopenapi-generatorで触ってる辺りがだめだ・・

**Comment by koutalou** [comment]
Resolved
