### ISSUE TITLE
Schedule API

### ISSUE THREAD

**Issue by haya14busa** [splathon/splathon-api#45]
やってるなう。

Schedule のしたにイベントのリストを持ちたいけどEventがSplathon自体のEventとかぶって若干悩み中

**Comment by knagayama** [comment]
10/06: スケジュールインターフェース&ダミーデータ
-10/13: スケジュール編集実装 & 予選マッチング実装
10/13-: Clould SQL 移行 & X11の実データ入力

**Comment by haya14busa** [comment]
一応このissueはSchedule APIに関してだけなので全体をトラックするissueではないですね。作るなら別にissue立てるとよさそう

**Comment by haya14busa** [comment]
ref: #51
